### ISSUE TITLE
Security hole with the commerce runtime administrator user

### ISSUE THREAD

**Issue by jflheureux** [Sitecore/Sitecore.Demo.Retail#44]
When following the [setup instructions](https://github.com/Sitecore/Sitecore.Demo.Retail/wiki/01.-Getting-Started), it is recommended to install Sitecore Commerce using the provided `install-commerce-server.ps1` script.

This script creates a new local user (HabitatRunTimeUser) and adds it to the local administrators group. The default password for this user is "pass@word1".

I agree it is mentioned that this is the default password and it can be changed. However, I believe most of the people who will clone this repository won't change the default values. This means that if an attacker knows you have this repository setup, he can log in as this administrator user.

Is there a reason the user needs to be an administrator in the first place?

The best practice would be to ask for a password when running the script or allow one to be provided in the command line options. Another option would be to generate a random password in the script.

**Comment by jflsitecore** [comment]
Although I wouldn't call it necessarily a "hole" we agree that it's a security weakness or vulnerability.

The history for running it as an Administrator stems back from the days of Microsoft Commerce Server and definitely need to be addressed.

Another suggestion would be to configure the "Deny log on locally" and "Deny Logon through Terminal Services" Local Security Policies for the HabitatRuntimeUser (just a quick fix for hardening the environment after the initial installation).

We will leave the issue open and address it in the coming weeks.

**Comment by jflsitecore** [comment]
Added some warning text in the Wiki about changing the default password stating that the user is created with administrative privileges. Also recommended to set the Deny log on through Remote Desktop Services and Deny log on locally to the HabitatRuntimeUser (after the installation has been completed)

**Comment by jflheureux** [comment]
Thanks. This should at least educate people about the risks involved in the setup of this project.

**Comment by jflsitecore** [comment]
New instructions warn of administrative rights
New scripts remove log on permissions for default user.
With the above mitigation measures put in place, and the fact that this project is meant for demo / non-production purposes, I'm marking this issue as closed. Thanks @jflheureux for bringing it up.
