### ISSUE TITLE
Scripts doesn't install order web service.

### ISSUE THREAD

**Issue by sandeepfis** [Sitecore/Sitecore.Demo.Retail#71]
Installation script doesn't install Order and Marketing web services. These scripts installs only Catalog and profile web services. Please guide how to install order and marketing web services. I tried through powershell command but it's showing below warning:

The Commerce Server site 'Habitat' does not contain a resource named 'Transactions'.

**Comment by heardk** [comment]
Sitecore Commerce 8.2.1 doesn't use the orders and marketing resources of Commerce Server anymore. Orders, Promotions and Pricing are all part of the new Commerce Engine. Catalog and Profile is the only part of CS being used for this release.

**Comment by sandeepfis** [comment]
Where does all orders store if we don't use Order web service?
