### ISSUE TITLE
install-commerce-sites.ps1 failing at Step 16: Bootstrap Commerce Engine and Initialise Environments

### ISSUE THREAD

**Issue by demiurgency** [Sitecore/Sitecore.Demo.Retail#74]
Hi.  I have been trying to set up Sitecore.Demo.Retail on my workstation following the steps from wiki/01.-Getting-Started.  I am using all configuration defaults (working directories, site name, etc.)  The installation goes fine until step 8 where the ps1 script throws the following error:

-----------
Webrequest content: {
  "@odata.context":"http://habitat.commerceengine.dev.local:5000/CommerceOps/$metadata#Commands/$entity","@odata.type":"#Sitecore.Commerce.Core.Commands.InitializeEnvironmentCommand","Id":"1916c31a15ab4e3eb1c8835020af0a1d","ResponseCode":"Error","Messages":[
    {
      "MessageDate":"2017-05-18T16:08:47.234743Z","Code":"Error","Text":"Management.block.getitemsbypath: Object reference not set to an instance of an object.","CommerceTermKey":"Exception"
    },{
      "MessageDate":"2017-05-18T16:08:47.2367407Z","Code":"Error","Text":"Currency set '{4B494292-598E-4A61-A156-D7501F7953ED}' was not found.","CommerceTermKey":"CurrencySetNotFound"
    }
--------------------
I can confirm {4B494292-598E-4A61-A156-D7501F7953ED} exists in Sitecore at /sitecore/Commerce/Commerce Control Panel/Shared Settings/Currency Settings/Currency Sets/All Currencies

Please help.  I am attaching the full output of the ps1 file in case it helps.  

[output1.txt](https://github.com/Sitecore/Sitecore.Demo.Retail/files/1011593/output1.txt)

**Comment by jflsitecore** [comment]
Could you also take a look at the sitecore logs and see what errors popped up in there?
When you did a gulp on Sitecore.Demo.Retail did any errors pop up?

**Comment by demiurgency** [comment]
No errors in Gulp output (attached).  Home page comes up, but any link off it returns a similar error.  Attaching log file and screenshot.  I'm having no luck figuring out how to debug the OData service.  I've been at this for over a day.  I appreciate the help.  I may just blow away the instance and try again from scratch.

![screenshot 2017-05-18 13 01 08](https://cloud.githubusercontent.com/assets/1130267/26214714/65acfd28-3bcb-11e7-9bea-642948370f7e.png)

[log.20170518.130226.txt](https://github.com/Sitecore/Sitecore.Demo.Retail/files/1011703/log.20170518.130226.txt)

[gulp-output.txt](https://github.com/Sitecore/Sitecore.Demo.Retail/files/1011706/gulp-output.txt)

**Comment by kazimnami** [comment]
Have a look at this post
http://kazimnami.azurewebsites.net/techblog/2017/03/02/currency-set-4b494292-598e-4a61-a156-d7501f7953ed-was-not-found/
. Specifically, see if you can access Sitecore via https, then look at the
log file in .net core iis site.

**Comment by mknayak** [comment]
@demiurgency 
Make sure you have followed all the instructions. 

Looks like the Pricer and PricerManager user doesn't have appropriate permission to access the items.
Commerce Engine uses these users to query pricing information.

Take a look into unicorn sync action. To wards end of sync it sets appropriate permissions for Pricer and PricerManager.

**Comment by demiurgency** [comment]
@mknayak and @kazimnami 
Thank you for the help.  Both posts were extremely helpful.  I've just now got the situation resolved.  As @mknayak suggested, the problem was the CommerceEngineUser was not being serialised into Sitecore.  After running unicorn from the control panel (not the script) I saw the below error:


![screenshot 2017-05-19 15 24 18](https://cloud.githubusercontent.com/assets/1130267/26263546/419e3028-3ca7-11e7-988a-073c89a66913.png)

1 non-fatal warning occurred during deserialization.
While loading master:/sitecore/content/Storefront/Retail Campaigns
The field 9b82216d-f53b-4558-b30a-e6952c8587f3 (likely Website Site Configuration Name) is not present in Sitecore on the Manager Root template.

The error was causing Project.Retail to kick out before deserialising the CommerceEnginUser and demoadmin users.  

Thanks again for the help.  The issue appears to be resolved.

**Comment by demiurgency** [comment]
Just a bit of after-analysis in case anyone runs in the same problem.
The root cause of all of this was during the initial install of Sitecore, I installed Email Experience Manager 3.2.1 rev. 160127.zip, which lacks the field **Website Site Configuration Name**.  This would have been avoided if I installed Email Experience Manager 3.4.1 rev. 170105.zip.
