### ISSUE TITLE
System.AccessViolationException after installing CS server via script

### ISSUE THREAD

**Issue by Nospamas** [Sitecore/Sitecore.Demo.Retail#77]
Encountered this while attempting to set up the Sitecore.Demo.Retail project. When spinning up the sitecore website following installation of commerce server via 'install-commerce-server.ps1' a "System.AccessViolationException" is thrown in mscorlib.dll. This happens each time the app-pool attempts to start and is fatal. The issue was fixed by repairing CS server via running the installation exe directly. I have not yet re-encountered the error having repaired.

The error occoured and was repeatable on the virtual box VM version of Windows 10 Professional (Licensed - Build 201612) 20 GB download available here: https://developer.microsoft.com/en-us/windows/downloads/virtual-machines

The system was updated to the latest patches via windows update prior to installation of sitecore and its dependencies. The error is not thrown on a pure sitecore instance, only once CS server is installed (as might be expected from the affecting dlls (see below).

The following are the full event details that appear in the event log. Maybe someone with more knowledge than I can shine a light on the issue.

Log Name:      Application
Source:        Microsoft-Windows-Perflib
Date:          2017-05-30 5:31:04 PM
Event ID:      1008
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      WinDev1612Sys
Description:
The Open Procedure for service "BITS" in DLL "C:\Windows\System32\bitsperf.dll" failed. Performance data for this service will not be available. The first four bytes (DWORD) of the Data section contains the error code.
Event Xml:
```xml
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Microsoft-Windows-Perflib" Guid="{13B197BD-7CEE-4B4E-8DD0-59314CE374CE}" EventSourceName="Perflib" />
    <EventID Qualifiers="49152">1008</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2017-05-31T00:31:04.783392000Z" />
    <EventRecordID>8677</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>WinDev1612Sys</Computer>
    <Security />
  </System>
  <UserData>
    <EventXML xmlns="Perflib">
      <param1>BITS</param1>
      <param2>C:\Windows\System32\bitsperf.dll</param2>
      <binaryDataSize>8</binaryDataSize>
      <binaryData>0500000000000000</binaryData>
    </EventXML>
  </UserData>
</Event>
```

Log Name:      Application
Source:        Microsoft-Windows-Perflib
Date:          2017-05-30 5:31:04 PM
Event ID:      1009
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      WinDev1612Sys
Description:
The Open Procedure for service "C:\Program Files\Commerce Server 11\Perf\cscustomperf.dll" in DLL "cscustomperf" generated an exception. Performance data for this service will not be available. The first four bytes (DWORD) of the Data section contains the exception code.
Event Xml:
```xml
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Microsoft-Windows-Perflib" Guid="{13B197BD-7CEE-4B4E-8DD0-59314CE374CE}" EventSourceName="Perflib" />
    <EventID Qualifiers="49152">1009</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2017-05-31T00:31:04.841718800Z" />
    <EventRecordID>8678</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>WinDev1612Sys</Computer>
    <Security />
  </System>
  <UserData>
    <EventXML xmlns="Perflib">
      <param1>C:\Program Files\Commerce Server 11\Perf\cscustomperf.dll</param1>
      <param2>cscustomperf</param2>
      <binaryDataSize>16</binaryDataSize>
      <binaryData>050000C0000000000CCB35D0F87F0000</binaryData>
    </EventXML>
  </UserData>
</Event>
```
Log Name:      Application
Source:        Microsoft-Windows-Perflib
Date:          2017-05-30 5:31:04 PM
Event ID:      1018
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      WinDev1612Sys
Description:
Disabled performance counter data collection for this session from the "cscustomperf" service because the performance counter library for that service has generated one or more errors. The errors that forced this action have been written to the application event log.
Event Xml:
```xml
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Microsoft-Windows-Perflib" Guid="{13B197BD-7CEE-4B4E-8DD0-59314CE374CE}" EventSourceName="Perflib" />
    <EventID Qualifiers="49152">1018</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2017-05-31T00:31:04.843846500Z" />
    <EventRecordID>8679</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>WinDev1612Sys</Computer>
    <Security />
  </System>
  <UserData>
    <EventXML xmlns="Perflib">
      <param1>cscustomperf</param1>
    </EventXML>
  </UserData>
</Event>
```

Log Name:      Application
Source:        .NET Runtime
Date:          2017-05-30 5:31:04 PM
Event ID:      1026
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      WinDev1612Sys
Description:
Application: w3wp.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException
   at Microsoft.Win32.Win32Native.RegQueryValueEx(Microsoft.Win32.SafeHandles.SafeRegistryHandle, System.String, Int32[], Int32 ByRef, Byte[], Int32 ByRef)
   at Microsoft.Win32.RegistryKey.InternalGetValue(System.String, System.Object, Boolean, Boolean)
   at Microsoft.Win32.RegistryKey.GetValue(System.String)
   at System.Diagnostics.PerformanceMonitor.GetData(System.String)
   at System.Diagnostics.PerformanceCounterLib.GetPerformanceData(System.String)
   at System.Diagnostics.PerformanceCounterLib.get_CategoryTable()
   at System.Diagnostics.PerformanceCounterLib.CategoryExists(System.String, System.String)
   at System.Diagnostics.PerformanceCounterCategory.Exists(System.String, System.String)
   at Sitecore.Diagnostics.PerformanceCounters.PerformanceCounter.DoInitialization(System.Object)
   at Sitecore.Threading.ManagedThreadPool.ProcessQueuedItems()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()

Event Xml:
```xml
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1026</EventID>
    <Level>2</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2017-05-31T00:31:04.862637100Z" />
    <EventRecordID>8680</EventRecordID>
    <Channel>Application</Channel>
    <Computer>WinDev1612Sys</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Application: w3wp.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException
   at Microsoft.Win32.Win32Native.RegQueryValueEx(Microsoft.Win32.SafeHandles.SafeRegistryHandle, System.String, Int32[], Int32 ByRef, Byte[], Int32 ByRef)
   at Microsoft.Win32.RegistryKey.InternalGetValue(System.String, System.Object, Boolean, Boolean)
   at Microsoft.Win32.RegistryKey.GetValue(System.String)
   at System.Diagnostics.PerformanceMonitor.GetData(System.String)
   at System.Diagnostics.PerformanceCounterLib.GetPerformanceData(System.String)
   at System.Diagnostics.PerformanceCounterLib.get_CategoryTable()
   at System.Diagnostics.PerformanceCounterLib.CategoryExists(System.String, System.String)
   at System.Diagnostics.PerformanceCounterCategory.Exists(System.String, System.String)
   at Sitecore.Diagnostics.PerformanceCounters.PerformanceCounter.DoInitialization(System.Object)
   at Sitecore.Threading.ManagedThreadPool.ProcessQueuedItems()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()

</Data>
  </EventData>
</Event>
```
Log Name:      Application
Source:        Application Error
Date:          2017-05-30 5:31:05 PM
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      WinDev1612Sys
Description:
Faulting application name: w3wp.exe, version: 10.0.14393.0, time stamp: 0x57899b8a
Faulting module name: csperfcounters.dll, version: 11.4.148.0, time stamp: 0x57d08705
Exception code: 0xc0000005
Fault offset: 0x000000000000cb0c
Faulting process id: 0x101c
Faulting application start time: 0x01d2d9a528dd7035
Faulting application path: c:\windows\system32\inetsrv\w3wp.exe
Faulting module path: C:\Program Files\Commerce Server 11\UPM\csperfcounters.dll
Report Id: 44626e14-c34a-463e-8b10-02619d29f5a4
Faulting package full name: 
Faulting package-relative application ID: 
Event Xml:
```xml
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2017-05-31T00:31:05.441850100Z" />
    <EventRecordID>8681</EventRecordID>
    <Channel>Application</Channel>
    <Computer>WinDev1612Sys</Computer>
    <Security />
  </System>
  <EventData>
    <Data>w3wp.exe</Data>
    <Data>10.0.14393.0</Data>
    <Data>57899b8a</Data>
    <Data>csperfcounters.dll</Data>
    <Data>11.4.148.0</Data>
    <Data>57d08705</Data>
    <Data>c0000005</Data>
    <Data>000000000000cb0c</Data>
    <Data>101c</Data>
    <Data>01d2d9a528dd7035</Data>
    <Data>c:\windows\system32\inetsrv\w3wp.exe</Data>
    <Data>C:\Program Files\Commerce Server 11\UPM\csperfcounters.dll</Data>
    <Data>44626e14-c34a-463e-8b10-02619d29f5a4</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>
```

**Comment by jflsitecore** [comment]
Some things to investigate that we've seen in the past:

Several POSSIBLE causes:

•	Anti-virus software running. In our internal test, we had to disable Trap before the CSConfig can work with perf counter
•	It MAY have something to do with the IIS 6 management compatibility feature is missing
•	Permission issue to access windows registry
•	A different VC++ redist package was installed

Also try to add the user to the Performance group in windows. I don't remember exactly which group but when you look up the groups should be obvious.

Let me know how it works out and hope this helps.

**Comment by Nospamas** [comment]
Other environments have not replicated it but it was repeatable on the Windows Development VM environment noted above. I'm fairly sure of the suggested fixes the last is the most likely.
