### ISSUE TITLE
Install Error : "The catalog set you specified does not exist."

### ISSUE THREAD

**Issue by skjain1983** [Sitecore/Sitecore.Demo.Retail#80]
I have been trying to install the sitecore demo retail site and this error seems to be blocking me.
also in the powershell script for installing commerce sites, it failes on a step to assign a user to a role, which again I am not sure how to proceed about this.

I have attached screenshots , any help would be appreciated

![pic1](https://user-images.githubusercontent.com/8365751/27164525-85e46f48-5153-11e7-8e1d-91a655523e57.PNG)
![pic2](https://user-images.githubusercontent.com/8365751/27164526-85e6af9c-5153-11e7-98e9-12feade74eda.PNG)

**Comment by jflsitecore** [comment]
Hello @skjain1983 , 
The errors you are seeing would be considered "fatal". Unfortunately there are many things that could be causing that. You should be able to successfully browse to the habitat.dev.local site **before** you run install-commerce-sites. If you can't reach the site then the next steps will fail. So something in the deployment of the demo site(s) failed.

**Comment by skjain1983** [comment]
Hello @jflsitecore 
Thanks, I reinstalled habitat and retail demo site, things appear to be stable.
FYI, I needed to switch from SOLR to lucene for my indexing to get it work, did not dive deep as to why SOLR was having issues.
