### ISSUE TITLE
Product Images Package

### ISSUE THREAD

**Issue by skjain1983** [Sitecore/Sitecore.Demo.Retail#83]
I was wondering where I could find the product Image package, currently my demo site does not have any product images

**Comment by skjain1983** [comment]
I took the bugs/images branch and got the serialized data for the product images.

**Comment by heardk** [comment]
There's an outstanding pull request for this. In the meantime, there's a zip with images in the Commerce Release package [here](https://dev.sitecore.net/Downloads/Sitecore_Commerce/821/Sitecore_Commerce_821.aspx) called Adventure Works images, that you can install after completing the setup of the demo site.

**Comment by jeanfrancoislarente** [comment]
Fixed with #67
